import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from "@/context";
import { Toaster } from "@/components/ui/toaster";
import Head from "next/head";

import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { CssBaseline, Box, Toolbar } from "@mui/material";

export const metadata: Metadata = {
  title: "Nhân viên",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <AppProviders>
          <CssBaseline />
          <Navbar />
          <Box sx={{ display: "flex" }}>
            <Sidebar />
            <Box
              component="main"
              sx={{ flexGrow: 1, p: 3, bgcolor: "transparent" }}
            >
              <Toolbar />
              {children}
            </Box>
          </Box>
          <Toaster />
        </AppProviders>
      </body>
    </html>
  );
}
