import Sidebar from "@/components/Sidebar";
import { AppProviders } from "@/context/AppProviders";
import { Box, CssBaseline } from "@mui/material";
import type { Metadata } from "next";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Nhân viên",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <AppProviders>
          <CssBaseline />

          <Box sx={{ display: "flex" }}>
            <Sidebar />
            <Box
              component="main"
              sx={{ flexGrow: 1, p: 4, bgcolor: "transparent" }}
            >
              {children}
            </Box>
          </Box>
        </AppProviders>
      </body>
    </html>
  );
}
